name: Sync Releases

on:
  pull_request:
    paths-ignore:
      - 'docs/**/*.json'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the sync on'
        required: true
        default: main

# Grant write permissions so we can commit updated JSON files
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out site repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Generate JSON endpoints
        run: |
          python scripts/generate.py \
            --owner warped-pinball \
            --repo vector \
            --out-dir docs

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Sync releases from vector @ ${{ github.run_id }}" || echo "Nothing to commit"
          # Push changes back to the appropriate branch
          git push origin HEAD:${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.head_ref }}

