name: Sync Releases

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-releases]

# Grant write permissions so we can commit updated JSON files
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out site repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Generate JSON endpoints
        run: |
          python scripts/generate.py \
            --owner warped-pinball \
            --repo vector \
            --out-dir docs

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Sync releases from vector @ ${{ github.run_id }}" || echo "Nothing to commit"
          # Push changes back to the same branch the workflow is running on
          git push origin HEAD:"${GITHUB_REF#refs/heads/}"
